### ISSUE TITLE
Job time summation runs into Raise 

### ISSUE THREAD

**Issue by AtzeDeVries** [AtzeDeVries/jobernetes#3]

**Comment by AtzeDeVries** [comment]
``` 2017-10-22 07:05:05,213 - jobernetes.jobexecutor - INFO - Job etl-crs-specimens took 1:50:51 2017-10-22 07:05:05,213 - jobernetes.jobexecutor - INFO - Job etl-forcemerge took 1:37:26 2017-10-22 07:05:05,213 - jobernetes.jobexecutor - INFO - Job etl-geo took 0:05:19 2017-10-22 07:05:05,213 - jobernetes.jobexecutor - INFO - Job etl-nsr took 0:03:51 2017-10-22 07:05:05,213 - jobernetes.jobexecutor - INFO - Job etl-storageunits took 0:01:13 Traceback (most recent call last):   File "jobernetes.py", line 29, in <module>     job_executor.start()   File "/jobernetes/jobexecutor.py", line 45, in start     self.__report()   File "/jobernetes/jobexecutor.py", line 68, in __report     time_taken = job.status.completion_time - job.status.start_time TypeError: unsupported operand type(s) for -: 'NoneType' and 'datetime.datetime' ```

**Comment by AtzeDeVries** [comment]
Sorting and/or subtracting of datetime objects it not working as expected. Removed 'usertime' for the moment.
